name: Build / CI / Deploy Snapshots

on:
  push:
    branches: [ master ]
    tags:
      - '!refs/tags/*'
    paths-ignore:
    - '**/README.md'
    - '**/.github/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '**/README.md'
    - '**/.github/**'
    
jobs:
  build-project:
    name: 'Build'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          check-latest: true

      - name: Build Java Project
        run: mvn install -P'release' -Dgpg.skip=true -Dlicense.skipUpdateLicense=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V --file pom.xml

      - name: Unit Tests
        run: mvn test

      - name: Integration Tests
        run: mvn verify

      - name: Set up Sonatype
        uses: actions/setup-java@v2
        with: # running setup-java again overwrites the settings.xml
          distribution: 'adopt'
          java-version: '11'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: SONATYPE_USERNAME # env variable for username in deploy
          server-password: SONATYPE_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_AUTHOR_PRIVATEKEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_AUTHOR_PASSPHRASE # env variable for GPG private key passphrase
          #settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Publish to Sonatype (Snapshots)
        if: github.event_name != 'pull_request' && github.event_name != 'release'
        run: mvn deploy -Dmaven.antrun.skip=true -DskipTests=true -Dlicense.skipUpdateLicense=true -Dmaven.javadoc.skip=true
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_AUTHOR_PASSPHRASE: ${{ secrets.GPG_AUTHOR_PASSPHRASE }}
